### ISSUE TITLE
Tool  එක off කරලා නේ බන්

### ISSUE THREAD

**Issue by teshiya28** [RazorKenway/R-Bomber#4]
![Screenshot_20220416-100726_Termux](https://user-images.githubusercontent.com/103806701/163661796-37dbda2e-8f0f-4e5f-ae9b-00c9b9c754bc.jpg)
Tool එක on කරන්න බැරිද 😢

**Comment by WhiteDraculaX** [comment]
Tool eka on karannako

**Comment by RazorKenway** [comment]
on karannam lagadima

**Comment by RazorKenway** [comment]
On කරා
